image: alpine:latest

stages:
    - test

test:
    script:
        - apk add nodejs npm
        # Install npm dependencies
        - node --version
        - npm --version
        - npm install
        # Build Frontend and Backend
        - npm run build:prod
