services:
    mongo:
        expose:
            - '27017'
        image: 'mongo:4'
        restart: 'unless-stopped'
    drawing:
        build:
            context: .
        links:
            - 'mongo'
        environment:
            MONGODB_CONNECTION_URI: mongodb://mongo/drawing
        ports:
            - '8080:8080'
        restart: 'unless-stopped'
version: '3'
