services:
    mongo:
        expose:
            - '27017'
        image: 'mongo:4'
        restart: 'unless-stopped'
    drawing:
        build:
            context: .
            # Overwrite defaults:
            # args:
            #    WEB_SOCKET_BASE_URI: ws://localhost:8080/
        links:
            - 'mongo'
        environment:
            DRAWING_MONGODB_CONNECTION_URI: mongodb://mongo/drawing
            # Overwrite defaults:
            # DRAWING_HTTP_PORT: 8080
            # DRAWING_SERVE_STATIC_FILES: true
        ports:
            - '8080:8080'
        restart: 'unless-stopped'
version: '3'
